/* eslint-disable indent */
export default [{
        code: 'Backquote',
        en: { lower: '`', upper: '~' },
        ru: { lower: 'ё', upper: 'Ё' },
        lower: '`',
        upper: '~',
    },
    {
        code: 'Digit1',
        en: { lower: '1', upper: '!' },
        ru: { lower: '1', upper: '!' },
        lower: '1',
        upper: '!',
    },
    {
        code: 'Digit2',
        en: { lower: '2', upper: '@' },
        ru: { lower: '2', upper: '"' },
        lower: '2',
        upper: '@',
    },
    {
        code: 'Digit3',
        en: { lower: '3', upper: '#' },
        ru: { lower: '3', upper: '№' },
        lower: '3',
        upper: '#',
    },
    {
        code: 'Digit4',
        en: { lower: '4', upper: '$' },
        ru: { lower: '4', upper: ';' },
        lower: '4',
        upper: '$',
    },
    {
        code: 'Digit5',
        en: { lower: '5', upper: '%' },
        ru: { lower: '5', upper: '%' },
        lower: '5',
        upper: '%',
    },
    {
        code: 'Digit6',
        en: { lower: '6', upper: '^' },
        ru: { lower: '6', upper: ':' },
        lower: '6',
        upper: '^',
    },
    {
        code: 'Digit7',
        en: { lower: '7', upper: '&' },
        ru: { lower: '7', upper: '?' },
        lower: '7',
        upper: '&',
    },
    {
        code: 'Digit8',
        en: { lower: '8', upper: '*' },
        ru: { lower: '8', upper: '*' },
        lower: '8',
        upper: '*',
    },
    {
        code: 'Digit9',
        en: { lower: '9', upper: '(' },
        ru: { lower: '9', upper: '(' },
        lower: '9',
        upper: '(',
    },
    {
        code: 'Digit0',
        lower: '0',
        en: { lower: '0', upper: ')' },
        ru: { lower: '0', upper: ')' },
        upper: ')',
    },
    {
        code: 'Minus',
        en: { lower: '-', upper: '_' },
        ru: { lower: '-', upper: '_' },
        lower: '-',
        upper: '_',
    },
    {
        code: 'Equal',
        en: { lower: '=', upper: '+' },
        ru: { lower: '=', upper: '+' },
        lower: '=',
        upper: '+',
    },
    {
        code: 'Backspace',
        lower: 'Backspace',
        upper: 'Backspace',
    },
    {
        code: 'Tab',
        lower: 'Tab',
        upper: 'Tab',
    },
    {
        code: 'KeyQ',
        en: { lower: 'q', upper: 'Q' },
        ru: { lower: 'й', upper: 'Й' },
        lower: 'q',
        upper: 'Q',
    },
    {
        code: 'KeyW',
        en: { lower: 'w', upper: 'W' },
        ru: { lower: 'ц', upper: 'Ц' },
        lower: 'w',
        upper: 'W',
    },
    {
        code: 'KeyE',
        en: { lower: 'e', upper: 'E' },
        ru: { lower: 'у', upper: 'У' },
        lower: 'e',
        upper: 'E',
    },
    {
        code: 'KeyR',
        en: { lower: 'r', upper: 'R' },
        ru: { lower: 'к', upper: 'К' },
        lower: 'r',
        upper: 'R',
    },
    {
        code: 'KeyT',
        en: { lower: 't', upper: 'T' },
        ru: { lower: 'е', upper: 'Е' },
        lower: 't',
        upper: 'T',
    },
    {
        code: 'KeyY',
        en: { lower: 'y', upper: 'Y' },
        ru: { lower: 'н', upper: 'Н' },
        lower: 'y',
        upper: 'Y',
    },
    {
        code: 'KeyU',
        en: { lower: 'u', upper: 'U' },
        ru: { lower: 'г', upper: 'Г' },
        lower: 'u',
        upper: 'U',
    },
    {
        code: 'KeyI',
        en: { lower: 'i', upper: 'I' },
        ru: { lower: 'ш', upper: 'Ш' },
        lower: 'i',
        upper: 'I',
    },
    {
        code: 'KeyO',
        en: { lower: 'o', upper: 'O' },
        ru: { lower: 'щ', upper: 'Щ' },
        lower: 'o',
        upper: 'O',
    },
    {
        code: 'KeyP',
        en: { lower: 'p', upper: 'P' },
        ru: { lower: 'з', upper: 'З' },
        lower: 'p',
        upper: 'P',
    },
    {
        code: 'BracketLeft',
        en: { lower: '[', upper: '{' },
        ru: { lower: 'х', upper: 'Х' },
        lower: '[',
        upper: '{',
    },
    {
        code: 'BracketRight',
        en: { lower: ']', upper: '}' },
        ru: { lower: 'ъ', upper: 'Ъ' },
        lower: ']',
        upper: '}',
    },
    {
        code: 'CapsLock',
        lower: 'CapsLock',
        upper: 'CapsLock',
    },
    {
        code: 'KeyA',
        en: { lower: 'a', upper: 'A' },
        ru: { lower: 'ф', upper: 'Ф' },
        lower: 'a',
        upper: 'A',
    },
    {
        code: 'KeyS',
        en: { lower: 's', upper: 'S' },
        ru: { lower: 'ы', upper: 'Ы' },
        lower: 's',
        upper: 'S',
    },
    {
        code: 'KeyD',
        en: { lower: 'd', upper: 'D' },
        ru: { lower: 'в', upper: 'В' },
        lower: 'd',
        upper: 'D',
    },
    {
        code: 'KeyF',
        en: { lower: 'f', upper: 'F' },
        ru: { lower: 'а', upper: 'А' },
        lower: 'f',
        upper: 'F',
    },
    {
        code: 'KeyG',
        en: { lower: 'g', upper: 'G' },
        ru: { lower: 'п', upper: 'П' },
        lower: 'g',
        upper: 'G',
    },
    {
        code: 'KeyH',
        en: { lower: 'h', upper: 'H' },
        ru: { lower: 'р', upper: 'Р' },
        lower: 'h',
        upper: 'H',
    },
    {
        code: 'KeyJ',
        en: { lower: 'j', upper: 'J' },
        ru: { lower: 'о', upper: 'О' },
        lower: 'j',
        upper: 'J',
    },
    {
        code: 'KeyK',
        en: { lower: 'k', upper: 'K' },
        ru: { lower: 'л', upper: 'Л' },
        lower: 'k',
        upper: 'K',
    },
    {
        code: 'KeyL',
        en: { lower: 'l', upper: 'L' },
        ru: { lower: 'д', upper: 'Д' },
        lower: 'l',
        upper: 'L',
    },
    {
        code: 'Semicolon',
        en: { lower: ';', upper: ':' },
        ru: { lower: 'ж', upper: 'Ж' },
        lower: ';',
        upper: ':',
    },
    {
        code: 'Quote',
        en: { lower: '\'', upper: '"' },
        ru: { lower: 'э', upper: 'Э' },
        lower: '\'',
        upper: '"',
    },
    {
        code: 'Enter',
        lower: 'Enter',
        upper: 'Enter',
    },
    {
        code: 'ShiftLeft',
        lower: 'Shift',
        upper: 'Shift',
    },
    {
        code: 'IntlBackslash',
        lower: '\\',
        upper: '|',
    },
    {
        code: 'KeyZ',
        en: { lower: 'z', upper: 'Z' },
        ru: { lower: 'я', upper: 'Я' },
        lower: 'z',
        upper: 'Z',
    },
    {
        code: 'KeyX',
        en: { lower: 'x', upper: 'X' },
        ru: { lower: 'ч', upper: 'Ч' },
        lower: 'x',
        upper: 'X',
    },
    {
        code: 'KeyC',
        en: { lower: 'c', upper: 'C' },
        ru: { lower: 'с', upper: 'С' },
        lower: 'c',
        upper: 'C',
    },
    {
        code: 'KeyV',
        en: { lower: 'v', upper: 'V' },
        ru: { lower: 'м', upper: 'М' },
        lower: 'v',
        upper: 'V',
    },
    {
        code: 'KeyB',
        en: { lower: 'b', upper: 'B' },
        ru: { lower: 'и', upper: 'И' },
        lower: 'b',
        upper: 'B',
    },
    {
        code: 'KeyN',
        en: { lower: 'n', upper: 'N' },
        ru: { lower: 'т', upper: 'Т' },
        lower: 'n',
        upper: 'N',
    },
    {
        code: 'KeyM',
        en: { lower: 'm', upper: 'M' },
        ru: { lower: 'ь', upper: 'Ь' },
        lower: 'm',
        upper: 'M',
    },
    {
        code: 'Comma',
        en: { lower: ',', upper: '<' },
        ru: { lower: 'б', upper: 'Б' },
        lower: ',',
        upper: '<',
    },
    {
        code: 'Period',
        en: { lower: '.', upper: '>' },
        ru: { lower: 'ю', upper: 'Ю' },
        lower: '.',
        upper: '>',
    },
    {
        code: 'Slash',
        en: { lower: '/', upper: '?' },
        ru: { lower: '.', upper: ',' },
        lower: '/',
        upper: '?',
    },
    {
        code: 'ShiftRight',
        lower: 'Shift',
        upper: 'Shift',
    },
    {
        code: 'ControlLeft',
        lower: 'Ctrl',
        upper: 'Ctrl',
    },
    {
        code: 'MetaLeft',
        lower: 'Win',
        upper: 'Win',
    },
    {
        code: 'AltLeft',
        lower: 'Alt',
        upper: 'Alt',
    },
    {
        code: 'Space',
        lower: 'Space',
        upper: 'Space',
    },
    {
        code: 'AltRight',
        lower: 'Alt',
        upper: 'Alt',
    },
    {
        code: 'MetaRight',
        lower: 'Win',
        upper: 'Win',
    },
    {
        code: 'ContextMenu',
        lower: 'Menu',
        upper: 'Menu',
    },

    {
        code: 'ControlRight',
        lower: 'Ctrl',
        upper: 'Ctrl',
    },
    {
        code: 'ArrowLeft',
        lower: '🠔',
        upper: '🠔',
    },
    {
        code: 'ArrowRight',
        lower: '🠖',
        upper: '🠖',
    },
    {
        code: 'ArrowUp',
        lower: '🠕',
        upper: '🠕',
    },
    {
        code: 'ArrowDown',
        lower: '🠗',
        upper: '🠗',
    },
];